version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    automerged_updates:
      - match:
        dependency_type: "all"
        update_type: "semver:minor"
